/* eslint-env browser */

import { TxtFile, DirFile, LinkFile } from './FileStructure';
import Shell from './Shell/Shell';
import ShellCommand from './Shell/Command';
import { print } from './util/io';

require('./styles.css');

const root = new DirFile('~', '~', null, null, null);
const links = new DirFile('links', '~/links', root, null, null);
const about = new TxtFile('about.txt', '~/about.txt', root, null, [`<p>Thanks for visiting my personal website. I'm currently looking for work as a web developer in Portland, OR. I have some experience with JS (Angular2, Ember), Python (Flask), and C# (aspnet core), and have dabbled a little with PHP (mostly using Silex). I also fearlessly welcome the challenge of learning new languages and frameworks. I'm primarily interested in fullstack/backend development.</p>`, `<p>Before beginning my career in development, I was a professional classical double bassist. I've performed with the Oregon and Eugene Symphonies, the Chintimini Chamber Music Festival, the Aspen Festival Orchestra, and many other professional ensembles.</p>`, `<ul><li><a href="mailto:egbertcarl@gmail.com">egbertcarl@gmail.com</a></li><li><a href="https://www.linkedin.com/in/carlegbert" target="blank">linkedin</a></li><li><a href="https://github.com/carlegbert" target="blank">github</a></li><li><a href="https://github.com/carlegbert/wwwterm-es6" target="blank">this site on gh</a></li></ul>`, `<p><span class="underline">About this site</span></p>`, `<p>This site is written in ES6 and transpiled with Babel/Webpack, with documentation generated by <a href="https://github.com/esdoc/esdoc">esdoc</a>.</p>`]);
const gh = new LinkFile('github', '~/links/github', links, null, 'https://github.com/carlegbert');
const linkedin = new LinkFile('linkedin', '~/links/linkedin', links, null, 'https://www.linkedin.com/in/carlegbert');
const email = new LinkFile('egbertcarl@gmail.com', '~/links/egbertcarl@gmail.com', links, null, 'mailto:egbertcarl@gmail.com');
const soundings = new LinkFile('gibson - soundings for double bass quartet', '~/links/soundings', links, null, 'https://www.youtube.com/watch?v=_VYZMzoVeZA');
links.children = [email, gh, linkedin, soundings];
root.children = [links, about];


document.addEventListener('DOMContentLoaded', () => {
  const shell = new Shell(root);
  const cursor = document.getElementById('shell-cursor');
  const PS1 = document.getElementById('PS1');
  const aboutBtn = document.getElementById('about-btn');
  const helpBtn = document.getElementById('help-btn');
  PS1.innerHTML = shell.getPS1String();

  let blinking = setInterval(() => {
    cursor.style.display = (cursor.style.display === 'none' ? '' : 'none');
  }, 700);

  document.onkeydown = (event) => {
    shell.parseKeystroke(event);
    cursor.style.display = '';
    clearInterval(blinking);
    blinking = setInterval(() => {
      cursor.style.display = (cursor.style.display === 'none' ? '' : 'none');
    }, 700);
  };

  aboutBtn.onclick = () => {
    const aboutRes = new ShellCommand('cat ~/about.txt', shell).cat();
    print(shell.getPS1String() + ' cat ~/about.txt', shell.outputElement);
    print(aboutRes.getDefaultOutput(), shell.outputElement);
  };

  helpBtn.onclick = () => {
    const helpRes = new ShellCommand('help').help();
    print(shell.getPS1String() + ' help', shell.outputElement);
    print(helpRes.getDefaultOutput(), shell.outputElement);
  };
});
